test: com/chriswarrick/roman_numerals/RomanNumerals.java com/chriswarrick/roman_numerals/RomanNumeralsTest.java
	javac com/chriswarrick/roman_numerals/RomanNumerals.java
	javac -cp .:junit-4.12.jar com/chriswarrick/roman_numerals/RomanNumeralsTest.java
	java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore com.chriswarrick.roman_numerals.RomanNumeralsTest
